Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Fabiane
// Data atual  : 08/05/2025
Var
// Seção de Declarações das variáveis 
nome: CARACTERE
num1, num2, num3: INTEIRO


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Olá, tudo bem?")
escreval ("Digite aqui seu nome:")
leia (nome)

escreval ("Bom dia,"
leia (nome)

Fimalgoritmo